[tool.poetry]
name = "custom-resources"
version = "1.1.10"
description = ""
authors = ["Amazon Web Services"]

[tool.poetry.dependencies]
python = ">3.9"
crhelper = "2.0.11"
requests = "2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
